"""eipd_policy_global_audit

Revision ID: d73f518cbe42
Revises: c62e407bad31
Create Date: 2026-10-07 13:35:14.526652

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d73f518cbe42"
down_revision: str | None = "c62e407bad31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eipd_policy_publications",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("policy_reference", sa.Text(), nullable=False),
        sa.Column("policy_hash", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("evidence_reference", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object' AND payload ? 'policy_version' AND payload ? 'policy_reference' AND payload->>'policy_version' = '1' AND payload->>'policy_reference' = policy_reference",
            name=op.f("ck_eipd_policy_publications_payload_identity"),
        ),
        sa.CheckConstraint(
            "policy_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_eipd_policy_publications_hash"),
        ),
        sa.CheckConstraint(
            "policy_reference ~ '[^[:space:]]'",
            name=op.f("ck_eipd_policy_publications_reference"),
        ),
        sa.CheckConstraint(
            "rationale ~ '[^[:space:]]' AND evidence_reference ~ '[^[:space:]]'",
            name=op.f("ck_eipd_policy_publications_evidence"),
        ),
        sa.CheckConstraint(
            "policy_version = 1",
            name=op.f("ck_eipd_policy_publications_policy_version"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["profiles.id"],
            name=op.f("fk_eipd_policy_publications_created_by_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eipd_policy_publications")),
        sa.UniqueConstraint(
            "id", "policy_hash", name=op.f("uq_eipd_policy_publications_id")
        ),
        sa.UniqueConstraint(
            "policy_reference",
            name=op.f("uq_eipd_policy_publications_policy_reference"),
        ),
    )
    op.create_table(
        "eipd_policy_selections",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("previous_revision", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("previous_publication_id", sa.UUID(), nullable=True),
        sa.Column("previous_policy_hash", sa.Text(), nullable=True),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("policy_hash", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("evidence_reference", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "rationale ~ '[^[:space:]]' AND evidence_reference ~ '[^[:space:]]'",
            name=op.f("ck_eipd_policy_selections_evidence"),
        ),
        sa.CheckConstraint(
            "(previous_revision = 0 AND previous_publication_id IS NULL AND previous_policy_hash IS NULL) OR (previous_revision > 0 AND previous_publication_id IS NOT NULL AND previous_policy_hash IS NOT NULL)",
            name=op.f("ck_eipd_policy_selections_previous_identity"),
        ),
        sa.CheckConstraint(
            "publication_id IS DISTINCT FROM previous_publication_id",
            name=op.f("ck_eipd_policy_selections_no_reselection"),
        ),
        sa.CheckConstraint(
            "revision > 0 AND previous_revision >= 0 AND revision = previous_revision + 1",
            name=op.f("ck_eipd_policy_selections_revision"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["profiles.id"],
            name=op.f("fk_eipd_policy_selections_created_by_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_revision", "previous_publication_id", "previous_policy_hash"],
            [
                "eipd_policy_selections.revision",
                "eipd_policy_selections.publication_id",
                "eipd_policy_selections.policy_hash",
            ],
            name=op.f(
                "fk_eipd_policy_selections_previous_revision_eipd_policy_selections"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["publication_id", "policy_hash"],
            ["eipd_policy_publications.id", "eipd_policy_publications.policy_hash"],
            name=op.f(
                "fk_eipd_policy_selections_publication_id_eipd_policy_publications"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eipd_policy_selections")),
        sa.UniqueConstraint(
            "publication_id", name=op.f("uq_eipd_policy_selections_publication_id")
        ),
        sa.UniqueConstraint(
            "revision",
            "publication_id",
            "id",
            name="uq_eipd_policy_selections_revision_publication_id",
        ),
        sa.UniqueConstraint(
            "revision",
            "publication_id",
            "policy_hash",
            name="uq_eipd_policy_selections_revision_publication_hash",
        ),
        sa.UniqueConstraint(
            "revision", name=op.f("uq_eipd_policy_selections_revision")
        ),
    )
    op.create_table(
        "eipd_policy_selector",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("selection_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_eipd_policy_selector_singleton")),
        sa.CheckConstraint(
            "revision > 0", name=op.f("ck_eipd_policy_selector_revision")
        ),
        sa.ForeignKeyConstraint(
            ["revision", "publication_id", "selection_id"],
            [
                "eipd_policy_selections.revision",
                "eipd_policy_selections.publication_id",
                "eipd_policy_selections.id",
            ],
            name=op.f("fk_eipd_policy_selector_revision_eipd_policy_selections"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eipd_policy_selector")),
    )
    op.execute(
        """DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='eipd_policy_admin') THEN
        CREATE ROLE eipd_policy_admin NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
          NOINHERIT NOREPLICATION NOBYPASSRLS;
      ELSIF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='eipd_policy_admin'
          AND (rolcanlogin OR rolsuper OR rolbypassrls OR rolcreaterole OR rolcreatedb)) THEN
        RAISE EXCEPTION 'Rol eipd_policy_admin incompatible';
      END IF;
      IF pg_has_role('app_user', 'eipd_policy_admin', 'MEMBER') THEN
        RAISE EXCEPTION 'Runtime no puede asumir administracion EIPD';
      END IF;
    END $$"""
    )
    op.execute("GRANT USAGE ON SCHEMA public TO eipd_policy_admin")
    for table in (
        "eipd_policy_publications",
        "eipd_policy_selections",
        "eipd_policy_selector",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"REVOKE ALL ON {table} FROM PUBLIC, app_user, eipd_policy_admin")
        op.execute(f"GRANT SELECT ON {table} TO app_user")
        op.execute(f"GRANT SELECT, INSERT ON {table} TO eipd_policy_admin")
        op.execute(
            f"CREATE POLICY authenticated_read ON {table} FOR SELECT TO app_user USING (auth.uid() IS NOT NULL)"
        )
        op.execute(
            f"CREATE POLICY administration_read ON {table} FOR SELECT TO eipd_policy_admin USING (true)"
        )
        op.execute(
            f"CREATE POLICY administration_insert ON {table} FOR INSERT TO eipd_policy_admin WITH CHECK (true)"
        )
    op.execute("GRANT UPDATE ON eipd_policy_selector TO eipd_policy_admin")
    op.execute(
        "CREATE POLICY administration_update ON eipd_policy_selector FOR UPDATE TO eipd_policy_admin USING (true) WITH CHECK (true)"
    )
    op.execute(
        """CREATE FUNCTION check_eipd_policy_selector_consistency() RETURNS trigger
      LANGUAGE plpgsql AS $$
      DECLARE latest record;
      BEGIN
        SELECT revision, publication_id, id INTO latest FROM eipd_policy_selections
          ORDER BY revision DESC LIMIT 1;
        IF FOUND AND NOT EXISTS (SELECT 1 FROM eipd_policy_selector
          WHERE id=1 AND revision=latest.revision AND publication_id=latest.publication_id
          AND selection_id=latest.id) THEN
          RAISE EXCEPTION 'Selector EIPD no coincide con ultima seleccion' USING ERRCODE='23514';
        END IF;
        RETURN NULL;
      END $$"""
    )
    op.execute(
        "REVOKE ALL ON FUNCTION check_eipd_policy_selector_consistency() FROM PUBLIC"
    )
    for table, operations in (
        ("eipd_policy_selections", "INSERT"),
        ("eipd_policy_selector", "INSERT OR UPDATE"),
    ):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER {table}_consistent AFTER {operations} ON {table} DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_eipd_policy_selector_consistency()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER eipd_policy_selector_consistent ON eipd_policy_selector")
    op.execute(
        "DROP TRIGGER eipd_policy_selections_consistent ON eipd_policy_selections"
    )
    op.execute("DROP FUNCTION check_eipd_policy_selector_consistency()")
    # Rol NOLOGIN conservado: puede pertenecer a gestion externa de despliegue.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("eipd_policy_selector")
    op.drop_table("eipd_policy_selections")
    op.drop_table("eipd_policy_publications")
    # ### end Alembic commands ###
