"""eipd_confirmation_evidence

Revision ID: e84a629dcf53
Revises: d73f518cbe42
Create Date: 2026-10-07 13:47:49.127650

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e84a629dcf53"
down_revision: str | None = "d73f518cbe42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_eipd_publications_confirmation_binding",
        "eipd_policy_publications",
        ["id", "policy_version", "policy_reference", "policy_hash"],
    )
    op.create_unique_constraint(
        "uq_eipd_reviews_confirmation_binding",
        "eipd_resolution_reviews",
        [
            "id",
            "assessment_id",
            "organization_id",
            "document_hash",
            "context_hash",
            "policy_version",
            "policy_reference",
            "policy_hash",
            "decision",
        ],
    )
    op.create_table(
        "eipd_confirmation_evidence",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("selector_revision", sa.Integer(), nullable=False),
        sa.Column("selection_id", sa.UUID(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("policy_reference", sa.Text(), nullable=False),
        sa.Column("policy_hash", sa.Text(), nullable=False),
        sa.Column("document_hash", sa.Text(), nullable=False),
        sa.Column("context_hash", sa.Text(), nullable=False),
        sa.Column(
            "review_decision", sa.Text(), server_default="continuar", nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "policy_hash ~ '^[0-9a-f]{64}$' AND document_hash ~ '^[0-9a-f]{64}$' AND context_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_eipd_confirmation_evidence_hashes"),
        ),
        sa.CheckConstraint(
            "policy_reference ~ '[^[:space:]]'",
            name=op.f("ck_eipd_confirmation_evidence_policy_reference"),
        ),
        sa.CheckConstraint(
            "review_decision = 'continuar'",
            name=op.f("ck_eipd_confirmation_evidence_positive_review"),
        ),
        sa.CheckConstraint(
            "policy_version = 1 AND selector_revision > 0",
            name=op.f("ck_eipd_confirmation_evidence_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id", "organization_id"],
            ["legal_assessments.id", "legal_assessments.organization_id"],
            name=op.f("fk_eipd_confirmation_evidence_assessment_id_legal_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["profiles.id"],
            name=op.f("fk_eipd_confirmation_evidence_created_by_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_eipd_confirmation_evidence_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["publication_id", "policy_version", "policy_reference", "policy_hash"],
            [
                "eipd_policy_publications.id",
                "eipd_policy_publications.policy_version",
                "eipd_policy_publications.policy_reference",
                "eipd_policy_publications.policy_hash",
            ],
            name=op.f(
                "fk_eipd_confirmation_evidence_publication_id_eipd_policy_publications"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "review_id",
                "assessment_id",
                "organization_id",
                "document_hash",
                "context_hash",
                "policy_version",
                "policy_reference",
                "policy_hash",
                "review_decision",
            ],
            [
                "eipd_resolution_reviews.id",
                "eipd_resolution_reviews.assessment_id",
                "eipd_resolution_reviews.organization_id",
                "eipd_resolution_reviews.document_hash",
                "eipd_resolution_reviews.context_hash",
                "eipd_resolution_reviews.policy_version",
                "eipd_resolution_reviews.policy_reference",
                "eipd_resolution_reviews.policy_hash",
                "eipd_resolution_reviews.decision",
            ],
            name=op.f(
                "fk_eipd_confirmation_evidence_review_id_eipd_resolution_reviews"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["selector_revision", "publication_id", "selection_id"],
            [
                "eipd_policy_selections.revision",
                "eipd_policy_selections.publication_id",
                "eipd_policy_selections.id",
            ],
            name=op.f(
                "fk_eipd_confirmation_evidence_selector_revision_eipd_policy_selections"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eipd_confirmation_evidence")),
        sa.UniqueConstraint(
            "assessment_id", name=op.f("uq_eipd_confirmation_evidence_assessment_id")
        ),
    )
    op.create_index(
        "ix_eipd_confirmation_evidence_organization_id",
        "eipd_confirmation_evidence",
        ["organization_id"],
        unique=False,
    )
    op.execute("ALTER TABLE eipd_confirmation_evidence ENABLE ROW LEVEL SECURITY")
    op.execute(
        "REVOKE ALL ON eipd_confirmation_evidence FROM PUBLIC, app_user, eipd_policy_admin"
    )
    op.execute("GRANT SELECT, INSERT ON eipd_confirmation_evidence TO app_user")
    op.execute(
        "CREATE POLICY tenant_read ON eipd_confirmation_evidence FOR SELECT TO app_user USING (organization_id IN (SELECT auth_org_ids()))"
    )
    op.execute(
        """CREATE POLICY tenant_insert ON eipd_confirmation_evidence
      FOR INSERT TO app_user WITH CHECK (
        organization_id IN (SELECT auth_org_ids())
        AND created_by IN (SELECT id FROM profiles WHERE auth_user_id=auth.uid())
        AND EXISTS (SELECT 1 FROM legal_assessments a
          WHERE a.id=assessment_id AND a.organization_id=eipd_confirmation_evidence.organization_id
          AND a.status='borrador' AND a.eipd_resolution_assessment IS NOT NULL)
        AND EXISTS (SELECT 1 FROM eipd_policy_selector s
          JOIN eipd_policy_publications p ON p.id=s.publication_id
          WHERE s.id=1 AND s.revision=selector_revision
          AND s.publication_id=eipd_confirmation_evidence.publication_id
          AND s.selection_id=eipd_confirmation_evidence.selection_id
          AND p.payload->>'activation'='habilitada')
        AND review_id=(SELECT r.id FROM eipd_resolution_reviews r
          WHERE r.assessment_id=eipd_confirmation_evidence.assessment_id
          AND r.organization_id=eipd_confirmation_evidence.organization_id
          ORDER BY r.created_at DESC,r.id DESC LIMIT 1)
      )"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("eipd_confirmation_evidence")
    op.drop_constraint(
        "uq_eipd_reviews_confirmation_binding",
        "eipd_resolution_reviews",
        type_="unique",
    )
    op.drop_constraint(
        "uq_eipd_publications_confirmation_binding",
        "eipd_policy_publications",
        type_="unique",
    )
